name: HACS Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
